import Head from "next/head";
import { ReactNode } from "react";
import styles from "./ContentLayout.module.css";

export default function ContentLayout(props: { children: ReactNode }) {
  const { children } = props;

  return (
    <>
      <Head>
        <title>MovieDB</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div className={styles.container}>{children}</div>
      </div>
    </>
  );
}
